# serverless.yml

service: lender-service

plugins:
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

functions:
  app:
    warmup: true
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'